SELECT bookings, users FROM BOOKINGS
INNER JOIN USERS ON BOOKINGS.users = TRUE;

SELECT properties, reviews FROM PROPERTIES
LEFT JOIN properties ON PROPERTIES.id = PROPERTIES.id;

SELECT users, bookings FROM USERS
LEFT JOIN BOOKINGS ON BOOKINGS.users = TRUE
UNION
SELECT users, bookings FROM USERS
RIGHT JOIN BOOKINGS ON BOOKINGS.users = TRUE;